# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
      - v*-rc*
    exclude:
      - v*-dev*
      - v*-alpha*
      - v*-beta*

pool:
  vmImage: ubuntu-latest

variables:
  BuildConfiguration: 'Release'
  BuildProjects: '**/*.csproj'
  PushBranch: 'dev'

steps:
- checkout: self
  fetchTags: true

# 取得 Git 最新 Tag
- script: |
    echo "##[group]Fetching latest Git tag"
    TAG_FULL=$(git describe --tags --abbrev=0)
    echo "Git tag found: $TAG_NAME"
    TAG_NAME=$(echo "$TAG_FULL" | sed 's|.*/||')
    echo "Set version: $TAG_NAME"
    echo "##vso[task.setvariable variable=PACKAGE_VERSION]$TAG_NAME"
  displayName: "Extract Git Tag as Version"
  failOnStderr: true
  condition: succeeded()

# 安裝 .NET
- task: UseDotNet@2
  displayName: "Install .NET Versions"
  inputs:
    version: '6.x'

- task: UseDotNet@2
  displayName: "Install .NET Versions"
  inputs:
    version: '8.x'

- task: UseDotNet@2
  displayName: "Install .NET Versions"
  inputs:
    version: '9.x'
    
# 設定套件來源
- script: |
    dotnet nuget add source "https://api.nuget.org/v3/index.json" --name "nuget.org" --configfile nuget.config
    if [ -n "$(PrivateSource)" ]; then
      echo "Adding Private NuGet source: $(PrivateSource)"
      dotnet nuget add source "$(PrivateSource)" --name "Private" --username "AzureDevOps" --password "$(System.AccessToken)" --store-password-in-clear-text --configfile nuget.config
    fi
  displayName: 'Configure NuGet Sources'
  env:
    NUGET_CREDENTIALPROVIDERS_PLUGIN_HANDLING: ignore
    
# 還原套件
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '$(BuildProjects)'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'

# 建置專案
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(BuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'
    
# 建置套件
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Packages'
  inputs:
    command: 'pack'
    packagesToPack: '$(BuildProjects)'
    configuration: '$(BuildConfiguration)'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byEnvVar
    versionEnvVar: PACKAGE_VERSION

# 推送至 GitHub
# - script: |
    # echo "Configuring Git..."
    # git config --global user.email "$(GitHubUserMail)"
    # git config --global user.name "$(GitHubUserName)"
    # git fetch origin
    # git remote set-url origin https://$(GitHubToken)@github.com$(GitHubEndPoint)
    # echo "Pushing to $(PushBranch) branch..."
    # git push -u origin $(PushBranch)
  # displayName: "Push to GitHub $(PushBranch) branch"
  
# 推送套件到 Azure Artifacts（內部 Feed）
- script: |
    echo "🔁 正在推送套件到 Azure Artifacts Feed..."
    for pkg in $(Build.ArtifactStagingDirectory)/*.nupkg; do
      echo "📦 推送套件: $pkg"
      dotnet nuget push "$pkg" \
        --api-key $(System.AccessToken) \
        --source "$(PrivateSource)" \
        --skip-duplicate
    done
  displayName: 'Push NuGet Packages to Azure Artifacts'
  condition: and(succeeded(), ne(variables['PrivateSource'], ''))
  env:
    NUGET_CREDENTIALPROVIDERS_PLUGIN_HANDLING: ignore

# 推送套件到 nuget.org（外部 Feed）
- script: |
    echo "🔁 正在推送套件到 NuGet.org..."
    for pkg in $(Build.ArtifactStagingDirectory)/*.nupkg; do
      echo "📦 推送套件: $pkg"
      dotnet nuget push "$pkg" \
        --api-key $(NugetOrgApiKey) \
        --source "https://api.nuget.org/v3/index.json" \
        --skip-duplicate
    done
  displayName: 'Push NuGet Packages to NuGet.org'
  condition: and(succeeded(), ne(variables['NugetOrgApiKey'], ''))